---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: users-secret
  namespace: users
spec:
  encryptedData:
    session.signing.key: AgBQ1br+39nHJ1YiANzvFAjjaCThtfQe+OkG6UInGp9Hv881MgOk4+Kw1LPlW9BSFBCsJmIa8UA3aaIU2yVT4podrHRCPrrhwUucTwwLkZj8Y0Vqmsnu+idAXESvxLMS3lNZ+PPb2yZ/RNZl/LdjMEbkLsDwRHPM+1OCU99b/XJotXX9BVoBG5qQBfgX+drv2a4pQx5Mo2MZ/wbUQBmX6RKMfz1bRxFViIDC6OGoF0nmeSIN05QOyPzw0BWAY4vXZUZdjxax5za18B0a++AWIJ6LI1bM8C7nVEUkxluVD57/4cf1Jw0RHbj4XUu8NM4yv5ftkgzYaQ8+d4XUXW1D7BGpUyMNwVvJSnJnlS/QAMtVlR10LhbEssE4P2stizGdV1j6Fp4ztEzXuEnyRnA3ht4yJJWA2tqBhhyCcW4EH+WFpu0tg4AzU/6lduM65KuVZRnO+gLtG1qzJKNpfokpPbh3EmStNPotbdeCZbaxvncAbxUodf8WFTMXOt+lVrThN9b1WnUfvXnStgqGcb55g6vc3RQ0oYqlNIFh3bp9yvK7YT4nOG++HGC6K/HlsUj8U/Uv7rkc1UCrNfl3JceHw7DOe8goUvkIRDuAun21zVLkl22CITSHUXubkPZ3b3vg0qrUzAUOiAFRdpc9QOEmkeoXTJSYNf0NHOLIe/CNa67gJ06Vxfx25YNPO4AcrC6XEKfq6NSsN9nUiNvuVKx1yWHuYaucPLv30mkNr56nmFkk+WbiMjII3lJHJHmPeNwHtPUAs2Ou35lcS+X2PBFlkdGi
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: users-secret
      namespace: users
    type: Opaque
