apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
  namespace: identity
data:
  scylla.uri: identity-scylladb
  users-service.uri: users-service.users.svc.cluster.local:8080
  kafka.uri: kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092
